version: '3'

services:
  edge_node:
    build:
      context: .
      dockerfile: Dockerfile.edge
    ports:
      - "8000:8000"
    environment:
      - DJANGO_ENV=development

  central_node:
    build:
      context: .
      dockerfile: Dockerfile.central
    ports:
      - "8001:8001"
    environment:
      - DJANGO_ENV=development
    depends_on:
      - edge_node

  cloud_server:
    build:
      context: .
      dockerfile: Dockerfile.cloud
    ports:
      - "8002:8002"
    environment:
      - DJANGO_ENV=development
    depends_on:
      - central_node
