services:
  edge_node:
    build:
      context: .
      dockerfile: edge_node/Dockerfile.edge
    ports:
      - "8000:8000"
    environment:
      - DJANGO_ENV=development
      - KAFKA_BROKER=kafka:9092

  central_node:
    build:
      context: .
      dockerfile: central_edge_node/Dockerfile.central
    ports:
      - "8001:8001"
    environment:
      - DJANGO_ENV=development
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - edge_node
      - kafka

  cloud_server:
    build:
      context: .
      dockerfile: cloud_server/Dockerfile.cloud
    ports:
      - "8002:8002"
    environment:
      - DJANGO_ENV=development
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - central_node
      - kafka

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
    depends_on:
      - zookeeper
