# Generated by Django 3.2.25 on 2024-10-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymizedPatientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=100)),
                ('age', models.IntegerField()),
                ('heartrate', models.IntegerField(blank=True)),
                ('temperature', models.FloatField(blank=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=20)),
                ('glucose_level', models.FloatField(blank=True)),
                ('oxygen_level', models.FloatField(blank=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
