# Generated by Django 5.1.2 on 2024-10-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField()),
                ('heartrate', models.IntegerField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=20, null=True)),
                ('glucose_level', models.FloatField(blank=True, null=True)),
                ('oxygen_level', models.FloatField(blank=True, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
